[[getting-started]]
= Getting Started

[[getting-started_dependencies]]
== Dependencies

Artifacts are available on https://search.maven.org/search?q=r2dbc-proxy[Maven Central]:

[source,xml]
----
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-proxy</artifactId>
  <version>${version}</version>
</dependency>
----

If you prefer to use the latest snapshot of the upcoming major version, add the Maven snapshot repository
and declare the appropriate dependency version.

[source,xml]
----
<dependency>
  <groupId>io.r2dbc</groupId>
  <artifactId>r2dbc-proxy</artifactId>
  <version>${version}.BUILD-SNAPSHOT</version>
</dependency>

<repository>
  <id>sonatype-nexus-snapshots</id>
  <name>Sonatype OSS Snapshot Repository</name>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
----

[[getting-started_native-image]]
== Native Image Support

R2DBC Proxy supports https://www.graalvm.org/reference-manual/native-image/[GraalVM native image].
Proxy creation uses the JDK dynamic proxy by default, and this requires appropriate configuration in the
native-image environment.

The R2DBC Proxy JAR ships with the following configuration files:

* `META-INF/native-image/io.r2dbc/r2dbc-proxy/native-image.properties`
* `META-INF/native-image/io.r2dbc/r2dbc-proxy/proxy-config.json`

The native-image build automatically detects these https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#embedding-a-configuration-file[embedded configuration files] and configures dynamic proxy support for R2DBC Proxy.
